Repository NVombat/MusicApp, pull requests merged in 2022-03, with the labels that each got.

#127 :sparkles: add media player for the posts page
  client/src/components/Posts/Card.tsx
Labels: enhancement, frontend

#129 :wastebasket: server cleanup
  client/.env.example
  server/admins/issue_jwt.py
  server/admins/tests/test_jwt_adm.py
  server/admins/utils.py
  server/admins/validate_admins.py
  server/admins/views.py
  server/authentication/jwt.py
  server/authentication/tests/test_jwt.py
  server/authentication/utils.py
  server/authentication/validate.py
  server/authentication/views.py
  server/mainapp/aws.py
  server/mainapp/utils.py
  server/mainapp/views.py
  server/userprofile/utils.py
  server/userprofile/views.py
Labels: cleanup, backend

#130 :lock: fix error logging security issues
  server/admins/utils.py
  server/authentication/utils.py
  server/mainapp/aws.py
  server/mainapp/utils.py
  server/tests/test_app_apis.py
  server/tests/test_app_models.py
  server/userprofile/utils.py
Labels: bug, backend, high priority
