Repository NVombat/MusicApp, pull requests merged in 2022-01, with the labels that each got.

#93 :alien: upgrading to react router v6
  client/package.json
  client/src/App.tsx
  client/src/components/Auth/AuthForm.tsx
  client/src/components/Auth/ForgetPasswordForm.tsx
  client/src/components/ContactUs/Form.tsx
  client/src/components/Profile/ResetPasswordForm.tsx
  client/src/components/Profile/UpdateProfile.tsx
  client/src/components/Record/Upload.tsx
  client/src/components/shared/Navbar.tsx
  client/yarn.lock
Labels: approved, dependencies, javascript

#94 :rocket: settings update for deployment
  server/core/settings.py
Labels: approved, deployment

#95 fix contact us form body in FE
  client/src/components/ContactUs/Form.tsx
Labels: approved

#96 :bug: temp changes -> removed pagination and auth
  server/mainapp/models.py
  server/mainapp/utils.py
  server/mainapp/views.py
  server/userprofile/models.py
  server/userprofile/utils.py
  server/userprofile/views.py
Labels: approved

#98 :sparkles: improve auth and token management
  server/admins/issue_jwt.py
  server/admins/tests/__init__.py
  server/admins/tests/test_auth.py
  server/admins/tests/test_models.py
  server/admins/urls.py
  server/admins/utils.py
  server/admins/validate_admins.py
  server/admins/views.py
  server/authentication/jwt.py
  server/authentication/tests/test_jwt.py
  server/authentication/utils.py
  server/authentication/validate.py
  server/core/settings.py
  server/test_runner.py
Labels: approved

#100 :hammer: added admin generation script
  generate_admin.sh
  server/admins/create_admin.py
Labels: approved
